### PR TITLE
Added a few options to delete, update Solr docs and other options

### PR DESCRIPTION
**Pull request by hguillermo**
Hi,

I made a lot of changes to use features included in Solr 4.x and up. These changes are:
1. Added  updateDoc method
2. Added a deleteDoc method (a single doc or an array of ids to delete)
3. Added a deleteDocByQuery (remove docs matching the query)
4. Added a method to delete a doc field

In the addDoc readme you are using addField but I think it should be setField?

I tested my code and updated the README. Let me know if you need some other clarification.

Thanks,

Harry

### CODE REVIEW

**Comment by rishabhmhjn** [comment]
@hguillermo Thanks for the pull-request.

Somehow, GitHub is not allowing me to merge your commits into the repository and shows me the following.

> This pull request cannot be automatically merged.

Maybe it is due to the changes that have been made in #2.
It will be great if you can merge that code into your repo and update this pull-request with your new merge commit.

**Comment by rishabhmhjn** [comment]
@hguillermo Never mind. I am doing the merging myself as I have to bump up the NPM version number to 0.0.4 too. Will update in a few minutes. Thanks again for the enhancements.

**Comment by rishabhmhjn** [comment]
@hguillermo I have merged your code and updated the npm package [helios](https://npmjs.org/package/helios) also.
Thanks for these updates again. If you find anything wrong, please let me know.

**Comment by hguillermo** [comment]
Hi rishabhmhjn,

Thanks for that. I am working with this version to do changes in my stage Solr db and if I find something I will let you know. Thanks for the fast updates!

Harry

**Pull request merged**
